// <auto-generated />
using System;
using DevHabits.api.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DevHabits.api.Migrations.Application
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260815025500_SeedingTagsData")]
    partial class SeedingTagsData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dev_habits")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DevHabits.api.Entities.Habit", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit")
                        .HasColumnName("is_archived");

                    b.Property<DateTime?>("LastCompletedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_completed_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_habits");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_habits_name");

                    b.ToTable("habits", "dev_habits");

                    b.HasData(
                        new
                        {
                            Id = "habit-001",
                            CreatedAtUtc = new DateTime(2026, 8, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Drink at least 2 liters of water per day",
                            IsArchived = false,
                            Name = "Drink Water",
                            Status = 1,
                            Type = 2
                        },
                        new
                        {
                            Id = "habit-002",
                            CreatedAtUtc = new DateTime(2026, 8, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Read 20 pages every day",
                            IsArchived = false,
                            Name = "Read Books",
                            Status = 1,
                            Type = 2
                        },
                        new
                        {
                            Id = "habit-003",
                            CreatedAtUtc = new DateTime(2026, 8, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Complete four workouts per week",
                            IsArchived = false,
                            Name = "Exercise",
                            Status = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = "habit-004",
                            CreatedAtUtc = new DateTime(2026, 8, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Meditate for 10 minutes every day",
                            IsArchived = false,
                            Name = "Meditate",
                            Status = 1,
                            Type = 2
                        },
                        new
                        {
                            Id = "habit-005",
                            CreatedAtUtc = new DateTime(2026, 8, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Avoid eating fast food",
                            IsArchived = false,
                            Name = "No Fast Food",
                            Status = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = "habit-006",
                            CreatedAtUtc = new DateTime(2026, 8, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Practice backend development for one hour",
                            IsArchived = false,
                            Name = "Practice Coding",
                            Status = 1,
                            Type = 2
                        },
                        new
                        {
                            Id = "habit-007",
                            CreatedAtUtc = new DateTime(2026, 8, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Run five kilometers three times per week",
                            IsArchived = false,
                            Name = "Running",
                            Status = 1,
                            Type = 2
                        },
                        new
                        {
                            Id = "habit-008",
                            CreatedAtUtc = new DateTime(2026, 8, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Call family twice per week",
                            IsArchived = false,
                            Name = "Call Family",
                            Status = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = "habit-009",
                            CreatedAtUtc = new DateTime(2026, 6, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Complete a backend development course",
                            IsArchived = false,
                            LastCompletedAtUtc = new DateTime(2026, 8, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Complete Course",
                            Status = 2,
                            Type = 1,
                            UpdatedAtUtc = new DateTime(2026, 8, 7, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "habit-010",
                            CreatedAtUtc = new DateTime(2026, 8, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Study two hours every day",
                            IsArchived = false,
                            Name = "Study",
                            Status = 1,
                            Type = 2
                        });
                });

            modelBuilder.Entity("DevHabits.api.Entities.Tag", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_tags");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_tags_name");

                    b.ToTable("tags", "dev_habits");

                    b.HasData(
                        new
                        {
                            Id = "tag-001",
                            CreatedAtUtc = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Habits related to health and overall wellness",
                            Name = "Health"
                        },
                        new
                        {
                            Id = "tag-002",
                            CreatedAtUtc = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Habits related to exercise and physical activity",
                            Name = "Fitness"
                        },
                        new
                        {
                            Id = "tag-003",
                            CreatedAtUtc = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Habits related to studying and acquiring knowledge",
                            Name = "Learning"
                        },
                        new
                        {
                            Id = "tag-004",
                            CreatedAtUtc = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Habits related to productivity and efficiency",
                            Name = "Productivity"
                        },
                        new
                        {
                            Id = "tag-005",
                            CreatedAtUtc = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Habits related to mindfulness and mental well-being",
                            Name = "Mindfulness"
                        },
                        new
                        {
                            Id = "tag-006",
                            CreatedAtUtc = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Habits related to food and healthy eating",
                            Name = "Nutrition"
                        },
                        new
                        {
                            Id = "tag-007",
                            CreatedAtUtc = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Habits related to programming and software development",
                            Name = "Coding"
                        },
                        new
                        {
                            Id = "tag-008",
                            CreatedAtUtc = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Habits related to personal growth and development",
                            Name = "Personal"
                        },
                        new
                        {
                            Id = "tag-009",
                            CreatedAtUtc = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Habits related to family, friends, and relationships",
                            Name = "Social"
                        },
                        new
                        {
                            Id = "tag-010",
                            CreatedAtUtc = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Habits related to money and financial management",
                            Name = "Finance"
                        });
                });

            modelBuilder.Entity("DevHabits.api.Entities.Habit", b =>
                {
                    b.OwnsOne("DevHabits.api.Entities.Frequency", "Frequency", b1 =>
                        {
                            b1.Property<string>("HabitId")
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("id");

                            b1.Property<int>("TimePerPeriod")
                                .HasColumnType("int")
                                .HasColumnName("frequency_time_per_period");

                            b1.Property<int>("Type")
                                .HasColumnType("int")
                                .HasColumnName("frequency_type");

                            b1.HasKey("HabitId");

                            b1.ToTable("habits", "dev_habits");

                            b1.WithOwner()
                                .HasForeignKey("HabitId")
                                .HasConstraintName("fk_habits_habits_id");

                            b1.HasData(
                                new
                                {
                                    HabitId = "habit-001",
                                    TimePerPeriod = 1,
                                    Type = 1
                                },
                                new
                                {
                                    HabitId = "habit-002",
                                    TimePerPeriod = 1,
                                    Type = 1
                                },
                                new
                                {
                                    HabitId = "habit-003",
                                    TimePerPeriod = 4,
                                    Type = 2
                                },
                                new
                                {
                                    HabitId = "habit-004",
                                    TimePerPeriod = 1,
                                    Type = 1
                                },
                                new
                                {
                                    HabitId = "habit-005",
                                    TimePerPeriod = 1,
                                    Type = 1
                                },
                                new
                                {
                                    HabitId = "habit-006",
                                    TimePerPeriod = 1,
                                    Type = 1
                                },
                                new
                                {
                                    HabitId = "habit-007",
                                    TimePerPeriod = 3,
                                    Type = 2
                                },
                                new
                                {
                                    HabitId = "habit-008",
                                    TimePerPeriod = 2,
                                    Type = 2
                                },
                                new
                                {
                                    HabitId = "habit-009",
                                    TimePerPeriod = 5,
                                    Type = 2
                                },
                                new
                                {
                                    HabitId = "habit-010",
                                    TimePerPeriod = 1,
                                    Type = 1
                                });
                        });

                    b.OwnsOne("DevHabits.api.Entities.Milestone", "Milestone", b1 =>
                        {
                            b1.Property<string>("HabitId")
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("id");

                            b1.Property<int>("Current")
                                .HasColumnType("int")
                                .HasColumnName("milestone_current");

                            b1.Property<int>("Target")
                                .HasColumnType("int")
                                .HasColumnName("milestone_target");

                            b1.HasKey("HabitId");

                            b1.ToTable("habits", "dev_habits");

                            b1.WithOwner()
                                .HasForeignKey("HabitId")
                                .HasConstraintName("fk_habits_habits_id");

                            b1.HasData(
                                new
                                {
                                    HabitId = "habit-001",
                                    Current = 8,
                                    Target = 30
                                },
                                new
                                {
                                    HabitId = "habit-002",
                                    Current = 260,
                                    Target = 1000
                                },
                                new
                                {
                                    HabitId = "habit-003",
                                    Current = 12,
                                    Target = 50
                                },
                                new
                                {
                                    HabitId = "habit-004",
                                    Current = 5,
                                    Target = 30
                                },
                                new
                                {
                                    HabitId = "habit-005",
                                    Current = 14,
                                    Target = 30
                                },
                                new
                                {
                                    HabitId = "habit-006",
                                    Current = 37,
                                    Target = 100
                                },
                                new
                                {
                                    HabitId = "habit-007",
                                    Current = 25,
                                    Target = 100
                                },
                                new
                                {
                                    HabitId = "habit-009",
                                    Current = 40,
                                    Target = 40
                                },
                                new
                                {
                                    HabitId = "habit-010",
                                    Current = 18,
                                    Target = 30
                                });
                        });

                    b.OwnsOne("DevHabits.api.Entities.Target", "Target", b1 =>
                        {
                            b1.Property<string>("HabitId")
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("id");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("target_unit");

                            b1.Property<int>("Value")
                                .HasColumnType("int")
                                .HasColumnName("target_value");

                            b1.HasKey("HabitId");

                            b1.ToTable("habits", "dev_habits");

                            b1.WithOwner()
                                .HasForeignKey("HabitId")
                                .HasConstraintName("fk_habits_habits_id");

                            b1.HasData(
                                new
                                {
                                    HabitId = "habit-001",
                                    Unit = "liters",
                                    Value = 2
                                },
                                new
                                {
                                    HabitId = "habit-002",
                                    Unit = "pages",
                                    Value = 20
                                },
                                new
                                {
                                    HabitId = "habit-003",
                                    Unit = "workout",
                                    Value = 1
                                },
                                new
                                {
                                    HabitId = "habit-004",
                                    Unit = "minutes",
                                    Value = 10
                                },
                                new
                                {
                                    HabitId = "habit-005",
                                    Unit = "day",
                                    Value = 1
                                },
                                new
                                {
                                    HabitId = "habit-006",
                                    Unit = "minutes",
                                    Value = 60
                                },
                                new
                                {
                                    HabitId = "habit-007",
                                    Unit = "km",
                                    Value = 5
                                },
                                new
                                {
                                    HabitId = "habit-008",
                                    Unit = "call",
                                    Value = 1
                                },
                                new
                                {
                                    HabitId = "habit-009",
                                    Unit = "lesson",
                                    Value = 1
                                },
                                new
                                {
                                    HabitId = "habit-010",
                                    Unit = "hours",
                                    Value = 2
                                });
                        });

                    b.Navigation("Frequency")
                        .IsRequired();

                    b.Navigation("Milestone");

                    b.Navigation("Target")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
